version: "3.7"
services:
  cpachecker:
    build: .
    volumes:
      - "./src:/usr/app/src"
      - "./output:/usr/app/output"
      - "./build:/usr/app/build"
      - "./doc:/usr/app/doc"
      - "./config:/usr/app/config"
      - "./.vscode:/usr/app/.vscode"
      - "./.devcontainer:/usr/app/.devcontainer"
      - "./.idea:/usr/app/.idea"
      - "./.git:/usr/app/.git"
      - "../sv-benchmarks:/mnt/sv-benchmarks"
